import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from 'next-i18next.config'
import { GetStaticProps } from 'next'
import { staticData } from 'services'
import { HomePageData, MetaData } from 'services/static'
import HomeLayout from 'containers/HomePage/components/HomeLayout/HomeLayout'
import ProductGrid from '../components/ProductGrid/ProductGrid'
import ProductCarousel from '../containers/HomePage/components/ProductCarousel/ProductCarousel'

interface HomePageProps {
  meta: MetaData
  pageData: HomePageData
}

export default function Home({ meta, pageData }: HomePageProps) {
  return (
    <HomeLayout meta={meta} slides={pageData.homePage.slider}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Home page 32231</h1>

      <ProductGrid />
      <ProductCarousel />
    </HomeLayout>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const lang = locale ? locale : 'ru'

  const meta = await staticData.getMeta({ lang })
  const pageData = await staticData.getHomePage({ lang })

  return {
    props: {
      ...(await serverSideTranslations(lang, ['common'], nextI18NextConfig)),
      meta,
      pageData,
    },
  }
}
